FREERTOS_PORTABLE_ARM_CR5_DIR := $(GET_LOCAL_DIR)
INCLUDE += -I$(FREERTOS_PORTABLE_ARM_CR5_DIR) -I$(FREERTOS_PORTABLE_ARM_CR5_DIR)/GCC

ASMSRC += \
	$(FREERTOS_PORTABLE_ARM_CR5_DIR)/GCC/portASM.S \
	$(FREERTOS_PORTABLE_ARM_CR5_DIR)/GCC/freertos.S

SRC += \
	$(FREERTOS_PORTABLE_ARM_CR5_DIR)/port.c

