FREERTOS_PORTABLE_GCC_DIR := $(GET_LOCAL_DIR)
INCLUDE += -I$(FREERTOS_PORTABLE_GCC_DIR) -I$(FREERTOS_PORTABLE_GCC_DIR)/GCC

ASMSRC += \
	$(FREERTOS_PORTABLE_GCC_DIR)/GCC/portASM.S \
	$(FREERTOS_PORTABLE_GCC_DIR)/GCC/freertos.S

SRC += \
	$(FREERTOS_PORTABLE_GCC_DIR)/port.c

